### PR TITLE
Fix global tree cache

### LINKED ISSUE #271: Withdrawal merkle proof calculation
Withdrawal merkle proofs fail to be generated sometimes. In the integration tests block processing fails once or twice before a proof is successfully generated.

In this run block processing fails 11 times: [Logs 1](https://circleci.com/api/v1.1/project/github/zkopru-network/zkopru/2175/output/103/0?file=true&allocation-id=611008337871995e7fc6754a-0-build%2F54CEC6E2)

In this run block processing fails 7 times: [Logs 2](https://circleci.com/api/v1.1/project/github/zkopru-network/zkopru/2165/output/103/0?file=true&allocation-id=610f1cfb9b3582255134eff9-0-build%2F3965BE0A)

In this run block processing fails 5 times: [Logs 3](https://circleci.com/api/v1.1/project/github/zkopru-network/zkopru/2145/output/103/0?file=true&allocation-id=610e2bf6d9791e7c89bda6c8-0-build%2F5B2DE8B9)

In this run block processing fails 6 times: [Logs 4](https://circleci.com/api/v1.1/project/github/zkopru-network/zkopru/2139/output/103/0?file=true&allocation-id=610e26557ffe2e72f2343b9e-0-build%2F10BE72B8)

This is almost certainly a race condition. This causes the error during block processing, then the database transaction is rolled back, and then the node tries again. This repeats until conditions are correct and the merkle proof is successfully generated.

I cannot reproduce this on my local machine, suggesting it's made worse by the lower CPU/memory resources in the CI environment.

### PR DESCRIPTION
**Pull request by JChanceHud**
The global tree cache is causing multiple nodes in a single process to modify each others data. This is fixed by creating tree cache instances for each grove instance.

Moves tree cache from `database` package to `tree` package.

Closes #271

### CODE REVIEW

File: packages/integration-test/tests/cases/context.ts [hunk 1]
```diff
@@ -63,15 +63,16 @@ export async function terminate(ctx: CtxProvider) {
...
-  provider.disconnect(0, 'exit')
   await Promise.all([
     coordinator.stop(),
     wallets.alice.node.stop(),
     wallets.bob.node.stop(),
     wallets.carl.node.stop(),
     wallets.coordinator.node.stop(),
   ])
-  await Promise.all([dbs.map(db => db.close())])
+  await new Promise(r => setTimeout(r, 20000))
```
Comment (wanseob) [inline packages/integration-test/tests/cases/context.ts:73]: what happens if we don't sleep here?

**Comment by wanseob** [comment]
Trees are sharing one cache of the grove instance right?
Changes look good to me!

File: packages/integration-test/tests/cases/context.ts (hunk 1 above)
Comment (JChanceHud) [reply packages/integration-test/tests/cases/context.ts:73]: This lets the nodes finish up any tasks that are currently running. Without this we get a bunch of `Connection not open on send` issues when the tests are ending.

[Without the fix](https://circleci.com/api/v1.1/project/github/zkopru-network/zkopru/2245/output/103/0?file=true&allocation-id=611374d71fb0f50ea20a6e0b-0-build%2F7E19B980)
[With the fix](https://circleci.com/api/v1.1/project/github/zkopru-network/zkopru/2275/output/103/0?file=true&allocation-id=6113807524e31916b181005c-0-build%2F1C15E1C9)
(look at the end of the logs)

**Review by sifnoc — APPROVED** [review]
LGTM!
